sudo: false

addons:
  apt:
    packages:
      - libgmp-dev
      - openjdk-6-jre

env:
 # - GHCVER=7.6.3  ESVER=1.6.0 # Deprecated
 # - GHCVER=7.8.3  ESVER=1.0.3 # Deprecated
 # - GHCVER=7.8.3  ESVER=1.1.2 # Deprecated
 # - GHCVER=7.8  ESVER=1.2.4 # deprecated
 - GHCVER=7.8  ESVER=1.3.6
 - GHCVER=7.8  ESVER=1.4.1
 - GHCVER=7.10 ESVER=1.5.2
 - GHCVER=7.10 ESVER=1.6.0
 - GHCVER=7.10 ESVER=1.7.2
 - GHCVER=8.0  ESVER=1.7.2

install:
  # stack
  - export STACK_YAML=stack-$GHCVER.yaml
  - mkdir -p ~/.local/bin
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v1.2.0/stack-1.2.0-linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - export PATH=~/.local/bin:$PATH
  - stack --version

  # elasticsearch
  - wget --no-check-certificate https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-$ESVER.tar.gz
  - tar xzf elasticsearch-$ESVER.tar.gz
  # set up a repo for snapshot testing. Required in ES >= 1.6
  - echo "path.repo = [\"/tmp\"]" >> ./elasticsearch-$ESVER/elasticsearch.yml
  - ./elasticsearch-$ESVER/bin/elasticsearch &

script:
  - stack setup
  - stack update
  - stack build
  - stack test bloodhound:doctests
  - stack test bloodhound:tests --test-arguments="--qc-max-successes 2000"

cache:
  directories:
  - $HOME/.stack
