sudo: false
language: generic

jdk:
  - oraclejdk11

addons:
  apt:
    packages:
      - libgmp-dev

env:
  matrix:
    - GHCVER=8.8  ESVER=5.6.0 STACK_YAML=stack.yaml DLINK=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch ES_JAVA_OPTS="-Xms500m -Xmx750m"

install:
  # stack
  - mkdir -p ~/.local/bin
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v2.1.3/stack-2.1.3-linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - export PATH=~/.local/bin:$PATH
  - stack --no-terminal --version
  # elasticsearch
  - wget --no-check-certificate $DLINK-$ESVER.tar.gz
  - tar xzf elasticsearch-$ESVER.tar.gz
  # set up a repo for snapshot testing. Required in ES >= 1.6
  - echo "path.repo = [\"/tmp\"]" >> ./elasticsearch-$ESVER/elasticsearch.yml
  - ./elasticsearch-$ESVER/bin/elasticsearch &

script:
  - stack setup --no-terminal
  - stack update --no-terminal
  - stack build -j2 --fast --no-terminal
  - travis_wait 60 sleep 1800 &
  - stack test --fast --no-terminal bloodhound:bloodhound-tests --test-arguments="--qc-max-success 500"

cache:
  timeout: 1500
  directories:
  - $HOME/.cabal
  - $HOME/.ghc
  - $HOME/.stack
  - .stack-work/
  apt: true
